const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../Resources/dist');let checks=0;const errors=[];
function check(ok,label){assert.ok(ok,label);checks++;console.log('PASS',label)}
(async()=>{const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');let content=fs.readFileSync(f);if(f.endsWith('index-i8K__Uke.js'))content=content.toString()+'\nwindow.__qa={eval:code=>eval(code)}';res.end(content)}catch{res.statusCode=404;res.end()}}).listen(8882,'127.0.0.1');const b=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});
try{
const p=await b.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8882/threes/');await p.getByRole('button',{name:'SKIP',exact:true}).click();
check(await p.locator('[data-inversion-key*=scale]').count()===0,'Threes Explore has no scale inversion picker');
await p.locator('[data-inversion-key="chord"] select').selectOption('1');
await p.evaluate(()=>{window.__played=[];for(const method of ['midiChordNow','pianoMidiNow']){const original=w[method];w[method]=function(m,...args){window.__played.push(...(Array.isArray(m)?m:[m]));return original.call(this,m,...args)}}});
await p.locator('[data-audition-chord]').first().click();await p.waitForTimeout(900);
console.log('ACTUAL',await p.evaluate(()=>({notes:window.__played,enabled:w.enabled,selected:h.get().selectedChord,inv:ctThreesCurrentScale().voicingInversion})));check(await p.evaluate(()=>window.__played.length>=3&&window.__played[0]%12===4&&window.__played.every(m=>[0,4,7,11].includes(m%12))),'Threes actual audition preserves C major and first inversion');
await p.evaluate(()=>{window.__played=[];w.playChordAudition([0,4,7],0)});await p.waitForTimeout(900);
check(await p.evaluate(()=>window.__played[0]%12===4&&window.__played.every(m=>[0,4,7,11].includes(m%12))),'Threes reference-aligned playback preserves inverted pitches');
const expected=await p.evaluate(()=>ctThreesChordMidis(h.get().selectedChord.pcs));check(expected[0]%12===4,'Threes first inversion has the third in the bass');
await p.locator('[data-explore-chord-pool]').click();check(await p.evaluate(expected=>j.saved.some(x=>JSON.stringify(x.midis)===JSON.stringify(expected)),expected),'Threes pool retains the chosen chord pitches');
await p.locator('[data-suite-stage="2"]').first().click();
check(await p.locator('[data-inversion-key*=scale]').count()===0,'Threes Generate has no scale inversion picker');
await p.locator('[data-inversion-key="chord"] select').selectOption('2');await p.locator('[data-working-chord-degree]').first().click();const generated=await p.evaluate(()=>ctThreesChordMidis(h.get().selectedChord.pcs));await p.locator('[data-generate-chord-pool]').click();check(await p.evaluate(x=>j.saved.some(y=>JSON.stringify(y.midis)===JSON.stringify(x)),generated),'Threes generated chord keeps its inversion in pool');
await p.locator('[data-suite-stage="3"]').first().click();const base=await p.evaluate(()=>Yt(h.get(),Z).midis);await p.locator('[data-inversion-key="compose-chord"] select').selectOption('1');let chord=await p.evaluate(()=>Yt(h.get(),Z));check(JSON.stringify(chord.midis)===JSON.stringify(await p.evaluate(base=>ctThreesInvertVoicing(base,ctThreesInversionOrder(Yt(h.get(),Z)),1),base)),'Threes composition picker puts the chord third in the bass');
await p.locator('[data-inversion-key="compose-chord"] select').selectOption('0');check(JSON.stringify(await p.evaluate(()=>Yt(h.get(),Z).midis))===JSON.stringify(base),'Threes root position restores the exact starting voicing');
await p.locator('[data-inversion-key="compose-chord"] select').selectOption('1');await p.locator('[data-compose-voicing-pool]').click();
check(await p.locator('[data-score-print]').count()===0,'Print button removed');await p.reload();await p.waitForTimeout(350);check(await p.evaluate(expected=>j.saved.some(x=>JSON.stringify(x.midis)===JSON.stringify(expected)),expected),'Threes saved pool survives reload');
await p.evaluate(async()=>{await w.ensure().suspend()});
await p.evaluate(()=>{w.enabled=true;w.playChordAudition([0,4,7])});await p.waitForTimeout(150);
check(await p.evaluate(()=>w.ctx.state==='running'),'Threes audio resumes from a suspended context');
await p.evaluate(()=>w.stop());check(await p.evaluate(()=>w.active.size===0),'Threes Stop clears active voices');
await p.close();
const i=await b.newPage({viewport:{width:1440,height:1000}});i.on('pageerror',e=>errors.push(e.message));await i.goto('http://127.0.0.1:8882/infinity/');await i.getByRole('button',{name:'SKIP',exact:true}).click();const ev=code=>i.evaluate(code=>window.__qa.eval(code),code);
check(await i.locator('[data-inversion-key*=scale]').count()===0,'Infinity Explore has no scale inversion picker');
await i.locator('[data-inversion-key="chord"] select').selectOption('1');const row=await i.locator('[data-degree-chord]').first().getAttribute('data-degree-chord');await i.locator('[data-material-chord-keep]').first().click();let pool=await ev('je[je.length-1].tones.map(t=>t.cents)');check(pool.every((x,j)=>Math.abs(x-row.split(',').map(Number)[j])<.00001),'Infinity pool matches the audible inverted chord');
await i.locator('[data-suite-stage="generate"]').click();check(await i.locator('[data-inversion-key*=scale]').count()===0,'Infinity Generate has no scale inversion picker');
await i.locator('[data-inversion-key="chord"] select').selectOption('1');
await ev('window.__playedInfinity=[]; window.__originalChord=v.playChord;v.playChord=function(tones,...args){window.__playedInfinity=tones.map(t=>t.cents);return window.__originalChord.call(this,tones,...args)};Ll()');
check(await ev('JSON.stringify(window.__playedInfinity)===JSON.stringify(ctInfinityPoolTones([...I].sort((a,b)=>a-b)).map(t=>t.cents))'),'Infinity selected-chord Play uses the selected inversion');
await i.locator('[data-sculpt-chord-add]').click();check(await ev('je.some(chord=>chord.tones[0].cents>0&&chord.tones.some(t=>t.cents>=p.equave))'),'Infinity generated chord stores lifted pitches');
await i.locator('[data-suite-stage="compose"]').click();if(!await i.locator('[data-compose-harmony-drawer]').evaluate(e=>e.open))await i.locator('[data-compose-harmony-drawer] > summary').click();await i.locator('[data-inversion-key="compose-chord"] select').selectOption('1');let draft=await ev('da().chordTones.map(t=>t.cents)');await i.locator('[data-compose-place-chord]').click();check(JSON.stringify(await ev('Y[Y.length-1].chordTones.map(t=>t.cents)'))===JSON.stringify(draft),'Infinity harmony rail retains chosen inversion');
check(await i.locator('[data-inversion-key*=scale],[data-inversion-key=compose-source],[data-inversion-key=compose-working]').count()===0,'Infinity Compose has no scale inversion picker');
check(await i.locator('input[type=file],[data-import-text],[data-export]').count()===0,'Infinity import/export controls removed');
await ev('v.ensure().suspend()');await i.locator('[data-inversion-key="compose-chord"] select').selectOption('1');await i.waitForTimeout(150);
check(await ev('v.ctx.state==="running"'),'Infinity audio resumes from a suspended context');
await ev('v.stop()');check(await ev('v.active.size===0&&v.timers.length===0'),'Infinity Stop clears active voices and scheduled notes');
const math=await i.evaluate(()=>{const c=ctInversions;return {triad:c.lift([60,64,67],1,12),seventh:c.lift([60,64,67,71],3,12),equave:c.tones([{cents:0,ratio:1,num:1,den:1},{cents:600,ratio:Math.sqrt(2)}],1,1200),tritave:c.tones([{cents:0,ratio:1},{cents:500,ratio:Math.pow(2,500/1200)},{cents:1000,ratio:Math.pow(2,1000/1200)}],2,1200*Math.log2(3))}});
check(JSON.stringify(math.triad)==='[64,67,72]'&&JSON.stringify(math.seventh)==='[71,72,76,79]','Triad and seventh inversions preserve pitch classes and raise wrapped voices');
check(math.equave[1].num===2&&math.equave[1].den===1,'Infinity lifted ratio labels match sounding frequencies');
check(Math.abs(math.tritave[1].ratio-3)<1e-8,'Infinity non-octave inversions use the tuning equave');
await i.close();check(errors.length===0,'No JavaScript runtime errors');console.log(JSON.stringify({checks,errors}));
}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
